Madara fixes
Paperback-iOS/extensions-madara pull request #29
Opened 2021-04-13 21:18 UTC by PythonCoderAS

Small fixes I made on the Madara base class, fixing bugs.

2021-04-13 21:24 UTC, PythonCoderAS commented
This change was made because some sources don't have enough manga to signal that pagination is finished, so Madara will request page 2 and so on, which are completely empty. If page 2 is empty, that for some reason signals to go onto page 3, and so on. This checks if the response is empty, and returns if it is.

https://github.com/Paperback-iOS/extensions-madara/blob/498002294d3c04f04a4b34c366d4e0beee9c58e1/src/Madara.ts#L175-L177

2021-04-13 21:25 UTC, PythonCoderAS commented
https://github.com/Paperback-iOS/extensions-madara/pull/29/files#diff-d2e73e5111a79b7f0a4eaad66f583ba22c5c9ff08e836ce1d275f3ec2e6ede9eR15-R22

2021-04-13 21:27 UTC, PythonCoderAS commented
Some sources, especially those that are made for 1-3 manga, don't have a method of finding the manga ID. In these cases, I override the Madara class's `getNumericID` function. These changes checks if the shortlink method of manga ID exists, and if it doesn't, a call to the source's `getNumerID` function is made. This required changing the method to async since the `getNumericID` function is async as well.
https://github.com/Paperback-iOS/extensions-madara/blob/498002294d3c04f04a4b34c366d4e0beee9c58e1/src/MadaraParser.ts#L15-L22

2021-04-13 21:28 UTC, PythonCoderAS commented
Some sources uses the `row` class to denote chapters rather than `wp-manga-chapter` class. I also moved the selector to not duplicate calls.
https://github.com/Paperback-iOS/extensions-madara/blob/498002294d3c04f04a4b34c366d4e0beee9c58e1/src/MadaraParser.ts#L70

2021-04-13 21:29 UTC, PythonCoderAS commented
The variable `should = chai.should()` is unused, so I used find and replace to delete it.

2021-04-13 21:33 UTC, GameFuzzy commented
> Some sources uses the `row` class to denote chapters rather than `wp-manga-chapter` class. I also moved the selector to not duplicate calls.
> 
> https://github.com/Paperback-iOS/extensions-madara/blob/498002294d3c04f04a4b34c366d4e0beee9c58e1/src/MadaraParser.ts#L70



> Some sources uses the `row` class to denote chapters rather than `wp-manga-chapter` class. I also moved the selector to not duplicate calls.
> 
> https://github.com/Paperback-iOS/extensions-madara/blob/498002294d3c04f04a4b34c366d4e0beee9c58e1/src/MadaraParser.ts#L70

Abstract this out

2021-04-13 21:36 UTC, GameFuzzy commented
> The variable `should = chai.should()` is unused, so I used find and replace to delete it.

This is just unnecessary imo.

2021-04-13 21:36 UTC, GameFuzzy commented
> This change was made because some sources don't have enough manga to signal that pagination is finished, so Madara will request page 2 and so on, which are completely empty. If page 2 is empty, that for some reason signals to go onto page 3, and so on. This checks if the response is empty, and returns if it is.
> 
> https://github.com/Paperback-iOS/extensions-madara/blob/498002294d3c04f04a4b34c366d4e0beee9c58e1/src/Madara.ts#L175-L177

Should be looked over by @nar1n

2021-04-13 21:37 UTC, PythonCoderAS commented
> > The variable `should = chai.should()` is unused, so I used find and replace to delete it.
> 
> This is just unnecessary imo.

It is but I don't see why there should be another PR to get rid of them. Also my IDE complains about "unused variables" when I leave them there.

2021-04-13 21:41 UTC, GameFuzzy commented
> > > The variable `should = chai.should()` is unused, so I used find and replace to delete it.
> > 
> > 
> > This is just unnecessary imo.
> 
> It is but I don't see why there should be another PR to get rid of them. Also my IDE complains about "unused variables" when I leave them there.

It’s like that in every repo. Any test file should be able to just be copied and used for another source with few modifications. If someone wants to use `should` they shouldn’t need to import it.

2021-04-13 21:42 UTC, PythonCoderAS commented
All tests use `except` rather than should. Using should requires a bunch of the testing code to change regardless, since it's all written in terms of expect.

2021-04-13 21:46 UTC, GameFuzzy commented
> All tests use `except` rather than should. Using should requires a bunch of the testing code to change regardless, since it's all written in terms of expect.

Either way, we should keep the test files the same as they are everywhere else imo.

2021-04-15 16:46 UTC, GameFuzzy requested changes

2021-04-15 16:46 UTC, GameFuzzy commented on src/MadaraParser.ts
> +        let selector = $('li.'+source.chapterRowClass);
Why are you doing this? If you're gonna give source control over the selector then give the source full control over the selector.

2021-04-15 16:48 UTC, PythonCoderAS commented on src/MadaraParser.ts
> +        let selector = $('li.'+source.chapterRowClass);
I see.

2021-04-15 20:14 UTC, ConradWeiser requested changes
I don't have too much of an issue with these changes. Sure, it's an adaptation towards a niche subset of Madara sources, but I don't see evidence that it'll break current Madara sources.

Provided that the documentation is detailed out a little more, I'd be comfortable doing a rigor test in-app, and approving things if it works out.

2021-04-15 20:14 UTC, ConradWeiser commented on src/MadaraParser.ts
> +    async parseMangaDetails($: CheerioSelector, mangaId: string, source: Madara): Promise<Manga> {
Could you please comment your changes a little more extensively in the typescript files? Specifically for this method.
Parsing is very hard to read if you're a newcomer. When there's niche things like this being added in, it should have a detailed explanation of the preconditions where this logic would apply. 

This appears to be something very few sources use. As such, people trying to understand how to write a module for the grand majority of sources should have some kind of documentation informing them that this logic may not apply for them.

2021-04-15 20:14 UTC, ConradWeiser commented on src/Madara.ts
> +     * Different Madara sources use a different selector to denote chapter rows.
Elaborate a little more on this. What is a chapter row? What is the container `div` or such, which this is found in?
If I knew nothing about madara, this comment should help guide me to determine what this selector should be used for the source that I was implementing.

2021-04-16 03:57 UTC, ConradWeiser approved these changes
Very good documentation! Thanks!

2021-04-16 06:48 UTC, GameFuzzy approved these changes
yup, looks good

2021-04-16 06:55 UTC, merged